main: ca.docilecraft.Prefixed
name: Prefixed
author: Doggyroc
website: http://dev.bukkit.org/server-mods/prefixed/
version: 1.10
softdepend: [Vault, TagAPI]
permissions:
    Prefixed.colour:
        description: Allows talking in colour.
        default: op
    Prefixed.COLOUR.BLACK:
        default: false
    Prefixed.COLOUR.DBLUE:
        default: false
    Prefixed.COLOUR.DGREEN:
        default: false
    Prefixed.COLOUR.DAQUA:
        default: false
    Prefixed.COLOUR.DRED:
        default: false
    Prefixed.COLOUR.PURPLE:
        default: false
    Prefixed.COLOUR.GOLD:
        default: false
    Prefixed.COLOUR.GREY:
        default: false
    Prefixed.COLOUR.DGREY:
        default: false
    Prefixed.COLOUR.INDIGO:
        default: false
    Prefixed.COLOUR.BGREEN:
        default: false
    Prefixed.COLOUR.AQUA:
        default: false
    Prefixed.COLOUR.RED:
        default: false
    Prefixed.COLOUR.PINK:
        default: false
    Prefixed.COLOUR.YELLOW:
        default: false
    Prefixed.COLOUR.RANDOM:
        default: false
    Prefixed.COLOUR.BOLD:
        default: false
    Prefixed.COLOUR.STRIKE:
        default: false
    Prefixed.COLOUR.UNDERLINE:
        default: false
    Prefixed.COLOUR.ITALIC:
        default: false