main: ca.docilecraft.Prefixed
name: Prefixed
author: Doggyroc
version: 1.4
softdepend: [PermissionsEx, Vault]
permissions:
    Prefixed.colour:
        description: Allows talking in colour.
        dafault: op